# Generated by Django 3.1.12 on 2021-06-29 14:46

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LandingPage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "hero_header",
                    models.CharField(max_length=127, verbose_name="Заголовок слайдера"),
                ),
                (
                    "hero_text",
                    models.CharField(max_length=255, verbose_name="Текст слайдера"),
                ),
                (
                    "about_header",
                    models.CharField(
                        max_length=127, verbose_name="Заголовок раздела О нас"
                    ),
                ),
                ("about_text", models.TextField(verbose_name="Текст раздела О нас")),
                (
                    "about_photo",
                    models.ImageField(
                        upload_to="", verbose_name="Фото для раздела О нас"
                    ),
                ),
                (
                    "why_us_header",
                    models.CharField(
                        max_length=127, verbose_name="Заголовок раздела Почему мы"
                    ),
                ),
                (
                    "why_us_text",
                    models.TextField(verbose_name="Текст раздела Почему мы"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
