# Generated by Django 3.1.12 on 2021-06-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landingpage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="landingpage",
            name="about_header",
            field=models.CharField(
                max_length=127, verbose_name="Заголовок раздела 'О нас''"
            ),
        ),
        migrations.AlterField(
            model_name="landingpage",
            name="about_photo",
            field=models.ImageField(
                upload_to="frontpage/", verbose_name="Фото для раздела 'О нас'"
            ),
        ),
        migrations.AlterField(
            model_name="landingpage",
            name="about_text",
            field=models.TextField(verbose_name="Текст раздела 'О нас'"),
        ),
        migrations.AlterField(
            model_name="landingpage",
            name="why_us_header",
            field=models.CharField(
                max_length=127, verbose_name="Заголовок раздела 'Почему мы'"
            ),
        ),
        migrations.AlterField(
            model_name="landingpage",
            name="why_us_text",
            field=models.TextField(verbose_name="Текст раздела 'Почему мы'"),
        ),
    ]
