# Generated by Django 3.1.12 on 2021-06-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landingpage", "0002_auto_20210630_1724"),
    ]

    operations = [
        migrations.AddField(
            model_name="landingpage",
            name="more_info_header",
            field=models.CharField(
                blank=True, max_length=127, verbose_name="Заголовок раздела 'О нас''"
            ),
        ),
        migrations.AddField(
            model_name="landingpage",
            name="more_info_photo",
            field=models.ImageField(
                blank=True,
                upload_to="frontpage/",
                verbose_name="Фото для раздела 'О нас'",
            ),
        ),
        migrations.AddField(
            model_name="landingpage",
            name="more_info_text",
            field=models.TextField(blank=True, verbose_name="Текст раздела 'О нас'"),
        ),
    ]
