# Generated by Django 3.1.12 on 2021-07-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0004_auto_20210630_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='about_header_en',
            field=models.CharField(max_length=127, null=True, verbose_name="Заголовок раздела 'О нас''"),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='about_header_ru',
            field=models.CharField(max_length=127, null=True, verbose_name="Заголовок раздела 'О нас''"),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='about_text_en',
            field=models.TextField(null=True, verbose_name="Текст раздела 'О нас'"),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='about_text_ru',
            field=models.TextField(null=True, verbose_name="Текст раздела 'О нас'"),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='hero_header_en',
            field=models.CharField(max_length=127, null=True, verbose_name='Заголовок слайдера'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='hero_header_ru',
            field=models.CharField(max_length=127, null=True, verbose_name='Заголовок слайдера'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='hero_text_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст слайдера'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='hero_text_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст слайдера'),
        ),
    ]
