# Generated by Django 3.1.12 on 2021-07-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0005_auto_20210701_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='why_us_header_en',
            field=models.CharField(max_length=127, null=True, verbose_name="Заголовок раздела 'Почему мы'"),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='why_us_header_ru',
            field=models.CharField(max_length=127, null=True, verbose_name="Заголовок раздела 'Почему мы'"),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='why_us_text_en',
            field=models.TextField(null=True, verbose_name="Текст раздела 'Почему мы'"),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='why_us_text_ru',
            field=models.TextField(null=True, verbose_name="Текст раздела 'Почему мы'"),
        ),
    ]
