# Generated by Django 3.1.12 on 2021-07-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0006_auto_20210713_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='more_info_header_en',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name="Заголовок раздела 'Дополнительно''"),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='more_info_header_ru',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name="Заголовок раздела 'Дополнительно''"),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='more_info_text_en',
            field=models.TextField(blank=True, null=True, verbose_name="Текст раздела 'Дополнительно'"),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='more_info_text_ru',
            field=models.TextField(blank=True, null=True, verbose_name="Текст раздела 'Дополнительно'"),
        ),
    ]
