# Generated by Django 3.1.12 on 2021-07-15 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrontPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_header', models.CharField(max_length=127, verbose_name='Заголовок слайдера')),
                ('hero_header_ru', models.CharField(max_length=127, null=True, verbose_name='Заголовок слайдера')),
                ('hero_header_en', models.CharField(max_length=127, null=True, verbose_name='Заголовок слайдера')),
                ('hero_header_zh_cn', models.CharField(max_length=127, null=True, verbose_name='Заголовок слайдера')),
                ('hero_text', models.CharField(max_length=255, verbose_name='Текст слайдера')),
                ('hero_text_ru', models.CharField(max_length=255, null=True, verbose_name='Текст слайдера')),
                ('hero_text_en', models.CharField(max_length=255, null=True, verbose_name='Текст слайдера')),
                ('hero_text_zh_cn', models.CharField(max_length=255, null=True, verbose_name='Текст слайдера')),
                ('about_header', models.CharField(max_length=127, verbose_name="Заголовок раздела 'О нас''")),
                ('about_header_ru', models.CharField(max_length=127, null=True, verbose_name="Заголовок раздела 'О нас''")),
                ('about_header_en', models.CharField(max_length=127, null=True, verbose_name="Заголовок раздела 'О нас''")),
                ('about_header_zh_cn', models.CharField(max_length=127, null=True, verbose_name="Заголовок раздела 'О нас''")),
                ('about_text', models.TextField(verbose_name="Текст раздела 'О нас'")),
                ('about_text_ru', models.TextField(null=True, verbose_name="Текст раздела 'О нас'")),
                ('about_text_en', models.TextField(null=True, verbose_name="Текст раздела 'О нас'")),
                ('about_text_zh_cn', models.TextField(null=True, verbose_name="Текст раздела 'О нас'")),
                ('about_photo', models.ImageField(upload_to='frontpage/', verbose_name="Фото для раздела 'О нас'")),
                ('why_us_header', models.CharField(max_length=127, verbose_name="Заголовок раздела 'Почему мы'")),
                ('why_us_header_ru', models.CharField(max_length=127, null=True, verbose_name="Заголовок раздела 'Почему мы'")),
                ('why_us_header_en', models.CharField(max_length=127, null=True, verbose_name="Заголовок раздела 'Почему мы'")),
                ('why_us_header_zh_cn', models.CharField(max_length=127, null=True, verbose_name="Заголовок раздела 'Почему мы'")),
                ('why_us_text', models.TextField(verbose_name="Текст раздела 'Почему мы'")),
                ('why_us_text_ru', models.TextField(null=True, verbose_name="Текст раздела 'Почему мы'")),
                ('why_us_text_en', models.TextField(null=True, verbose_name="Текст раздела 'Почему мы'")),
                ('why_us_text_zh_cn', models.TextField(null=True, verbose_name="Текст раздела 'Почему мы'")),
                ('more_info_header', models.CharField(blank=True, max_length=127, verbose_name="Заголовок раздела 'Дополнительно''")),
                ('more_info_header_ru', models.CharField(blank=True, max_length=127, null=True, verbose_name="Заголовок раздела 'Дополнительно''")),
                ('more_info_header_en', models.CharField(blank=True, max_length=127, null=True, verbose_name="Заголовок раздела 'Дополнительно''")),
                ('more_info_header_zh_cn', models.CharField(blank=True, max_length=127, null=True, verbose_name="Заголовок раздела 'Дополнительно''")),
                ('more_info_text', models.TextField(blank=True, verbose_name="Текст раздела 'Дополнительно'")),
                ('more_info_text_ru', models.TextField(blank=True, null=True, verbose_name="Текст раздела 'Дополнительно'")),
                ('more_info_text_en', models.TextField(blank=True, null=True, verbose_name="Текст раздела 'Дополнительно'")),
                ('more_info_text_zh_cn', models.TextField(blank=True, null=True, verbose_name="Текст раздела 'Дополнительно'")),
                ('more_info_photo', models.ImageField(blank=True, upload_to='frontpage/', verbose_name="Фото для раздела 'Дополнительно'")),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
