# Generated by Django 3.1.12 on 2021-07-15 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='announcement_zh_cn',
            new_name='announcement_zh_hans',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='event_program_zh_cn',
            new_name='event_program_zh_hans',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='subtitle_zh_cn',
            new_name='subtitle_zh_hans',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='title_zh_cn',
            new_name='title_zh_hans',
        ),
    ]
